/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as PipelinePlaceholderRouteImport } from './routes/pipeline-placeholder'
import { Route as DocumentationSingleCellRouteImport } from './routes/documentation-single-cell'
import { Route as DocumentationBulkRouteImport } from './routes/documentation-bulk'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SingleCellIndexRouteImport } from './routes/single-cell.index'
import { Route as SingleCellFormatIdRouteImport } from './routes/single-cell.$formatId'
import { Route as PipelineUmiMiseq2x250RouteImport } from './routes/pipeline.umi-miseq-2x250'
import { Route as PipelineRaceMiseq325275RouteImport } from './routes/pipeline.race-miseq-325-275'
import { Route as PipelineNonumiMiseq2x250RouteImport } from './routes/pipeline.nonumi-miseq-2x250'
import { Route as PipelineCustomBulkRouteImport } from './routes/pipeline.custom-bulk'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinePlaceholderRoute = PipelinePlaceholderRouteImport.update({
  id: '/pipeline-placeholder',
  path: '/pipeline-placeholder',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationSingleCellRoute = DocumentationSingleCellRouteImport.update({
  id: '/documentation-single-cell',
  path: '/documentation-single-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationBulkRoute = DocumentationBulkRouteImport.update({
  id: '/documentation-bulk',
  path: '/documentation-bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleCellIndexRoute = SingleCellIndexRouteImport.update({
  id: '/single-cell/',
  path: '/single-cell/',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleCellFormatIdRoute = SingleCellFormatIdRouteImport.update({
  id: '/single-cell/$formatId',
  path: '/single-cell/$formatId',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineUmiMiseq2x250Route = PipelineUmiMiseq2x250RouteImport.update({
  id: '/pipeline/umi-miseq-2x250',
  path: '/pipeline/umi-miseq-2x250',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRaceMiseq325275Route = PipelineRaceMiseq325275RouteImport.update({
  id: '/pipeline/race-miseq-325-275',
  path: '/pipeline/race-miseq-325-275',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineNonumiMiseq2x250Route =
  PipelineNonumiMiseq2x250RouteImport.update({
    id: '/pipeline/nonumi-miseq-2x250',
    path: '/pipeline/nonumi-miseq-2x250',
    getParentRoute: () => rootRouteImport,
  } as any)
const PipelineCustomBulkRoute = PipelineCustomBulkRouteImport.update({
  id: '/pipeline/custom-bulk',
  path: '/pipeline/custom-bulk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/documentation': typeof DocumentationRoute
  '/documentation-bulk': typeof DocumentationBulkRoute
  '/documentation-single-cell': typeof DocumentationSingleCellRoute
  '/pipeline-placeholder': typeof PipelinePlaceholderRoute
  '/track': typeof TrackRoute
  '/pipeline/custom-bulk': typeof PipelineCustomBulkRoute
  '/pipeline/nonumi-miseq-2x250': typeof PipelineNonumiMiseq2x250Route
  '/pipeline/race-miseq-325-275': typeof PipelineRaceMiseq325275Route
  '/pipeline/umi-miseq-2x250': typeof PipelineUmiMiseq2x250Route
  '/single-cell/$formatId': typeof SingleCellFormatIdRoute
  '/single-cell/': typeof SingleCellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/documentation': typeof DocumentationRoute
  '/documentation-bulk': typeof DocumentationBulkRoute
  '/documentation-single-cell': typeof DocumentationSingleCellRoute
  '/pipeline-placeholder': typeof PipelinePlaceholderRoute
  '/track': typeof TrackRoute
  '/pipeline/custom-bulk': typeof PipelineCustomBulkRoute
  '/pipeline/nonumi-miseq-2x250': typeof PipelineNonumiMiseq2x250Route
  '/pipeline/race-miseq-325-275': typeof PipelineRaceMiseq325275Route
  '/pipeline/umi-miseq-2x250': typeof PipelineUmiMiseq2x250Route
  '/single-cell/$formatId': typeof SingleCellFormatIdRoute
  '/single-cell': typeof SingleCellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/documentation': typeof DocumentationRoute
  '/documentation-bulk': typeof DocumentationBulkRoute
  '/documentation-single-cell': typeof DocumentationSingleCellRoute
  '/pipeline-placeholder': typeof PipelinePlaceholderRoute
  '/track': typeof TrackRoute
  '/pipeline/custom-bulk': typeof PipelineCustomBulkRoute
  '/pipeline/nonumi-miseq-2x250': typeof PipelineNonumiMiseq2x250Route
  '/pipeline/race-miseq-325-275': typeof PipelineRaceMiseq325275Route
  '/pipeline/umi-miseq-2x250': typeof PipelineUmiMiseq2x250Route
  '/single-cell/$formatId': typeof SingleCellFormatIdRoute
  '/single-cell/': typeof SingleCellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk'
    | '/documentation'
    | '/documentation-bulk'
    | '/documentation-single-cell'
    | '/pipeline-placeholder'
    | '/track'
    | '/pipeline/custom-bulk'
    | '/pipeline/nonumi-miseq-2x250'
    | '/pipeline/race-miseq-325-275'
    | '/pipeline/umi-miseq-2x250'
    | '/single-cell/$formatId'
    | '/single-cell/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk'
    | '/documentation'
    | '/documentation-bulk'
    | '/documentation-single-cell'
    | '/pipeline-placeholder'
    | '/track'
    | '/pipeline/custom-bulk'
    | '/pipeline/nonumi-miseq-2x250'
    | '/pipeline/race-miseq-325-275'
    | '/pipeline/umi-miseq-2x250'
    | '/single-cell/$formatId'
    | '/single-cell'
  id:
    | '__root__'
    | '/'
    | '/bulk'
    | '/documentation'
    | '/documentation-bulk'
    | '/documentation-single-cell'
    | '/pipeline-placeholder'
    | '/track'
    | '/pipeline/custom-bulk'
    | '/pipeline/nonumi-miseq-2x250'
    | '/pipeline/race-miseq-325-275'
    | '/pipeline/umi-miseq-2x250'
    | '/single-cell/$formatId'
    | '/single-cell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkRoute: typeof BulkRoute
  DocumentationRoute: typeof DocumentationRoute
  DocumentationBulkRoute: typeof DocumentationBulkRoute
  DocumentationSingleCellRoute: typeof DocumentationSingleCellRoute
  PipelinePlaceholderRoute: typeof PipelinePlaceholderRoute
  TrackRoute: typeof TrackRoute
  PipelineCustomBulkRoute: typeof PipelineCustomBulkRoute
  PipelineNonumiMiseq2x250Route: typeof PipelineNonumiMiseq2x250Route
  PipelineRaceMiseq325275Route: typeof PipelineRaceMiseq325275Route
  PipelineUmiMiseq2x250Route: typeof PipelineUmiMiseq2x250Route
  SingleCellFormatIdRoute: typeof SingleCellFormatIdRoute
  SingleCellIndexRoute: typeof SingleCellIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-placeholder': {
      id: '/pipeline-placeholder'
      path: '/pipeline-placeholder'
      fullPath: '/pipeline-placeholder'
      preLoaderRoute: typeof PipelinePlaceholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation-single-cell': {
      id: '/documentation-single-cell'
      path: '/documentation-single-cell'
      fullPath: '/documentation-single-cell'
      preLoaderRoute: typeof DocumentationSingleCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation-bulk': {
      id: '/documentation-bulk'
      path: '/documentation-bulk'
      fullPath: '/documentation-bulk'
      preLoaderRoute: typeof DocumentationBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-cell/': {
      id: '/single-cell/'
      path: '/single-cell'
      fullPath: '/single-cell/'
      preLoaderRoute: typeof SingleCellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single-cell/$formatId': {
      id: '/single-cell/$formatId'
      path: '/single-cell/$formatId'
      fullPath: '/single-cell/$formatId'
      preLoaderRoute: typeof SingleCellFormatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/umi-miseq-2x250': {
      id: '/pipeline/umi-miseq-2x250'
      path: '/pipeline/umi-miseq-2x250'
      fullPath: '/pipeline/umi-miseq-2x250'
      preLoaderRoute: typeof PipelineUmiMiseq2x250RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/race-miseq-325-275': {
      id: '/pipeline/race-miseq-325-275'
      path: '/pipeline/race-miseq-325-275'
      fullPath: '/pipeline/race-miseq-325-275'
      preLoaderRoute: typeof PipelineRaceMiseq325275RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/nonumi-miseq-2x250': {
      id: '/pipeline/nonumi-miseq-2x250'
      path: '/pipeline/nonumi-miseq-2x250'
      fullPath: '/pipeline/nonumi-miseq-2x250'
      preLoaderRoute: typeof PipelineNonumiMiseq2x250RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/custom-bulk': {
      id: '/pipeline/custom-bulk'
      path: '/pipeline/custom-bulk'
      fullPath: '/pipeline/custom-bulk'
      preLoaderRoute: typeof PipelineCustomBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkRoute: BulkRoute,
  DocumentationRoute: DocumentationRoute,
  DocumentationBulkRoute: DocumentationBulkRoute,
  DocumentationSingleCellRoute: DocumentationSingleCellRoute,
  PipelinePlaceholderRoute: PipelinePlaceholderRoute,
  TrackRoute: TrackRoute,
  PipelineCustomBulkRoute: PipelineCustomBulkRoute,
  PipelineNonumiMiseq2x250Route: PipelineNonumiMiseq2x250Route,
  PipelineRaceMiseq325275Route: PipelineRaceMiseq325275Route,
  PipelineUmiMiseq2x250Route: PipelineUmiMiseq2x250Route,
  SingleCellFormatIdRoute: SingleCellFormatIdRoute,
  SingleCellIndexRoute: SingleCellIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
